version: "3.4"

services:
  aisstream:
    image: aisstream
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - AMSA_MARIWEB_USERNAME=${AMSA_MARIWEB_USERNAME}
        - AMSA_MARIWEB_UPASSWORD=${AMSA_MARIWEB_UPASSWORD}
        - AMSA_MARIWEB_URI=${AMSA_MARIWEB_URI}
        - AISSTREAM_BOUNDARY_LAT1=${AISSTREAM_BOUNDARY_LAT1}
        - AISSTREAM_BOUNDARY_LON1=${AISSTREAM_BOUNDARY_LON1}
        - AISSTREAM_BOUNDARY_LAT2=${AISSTREAM_BOUNDARY_LAT2}
        - AISSTREAM_BOUNDARY_LON2=${AISSTREAM_BOUNDARY_LON2}
        - AISSTREAM_BOUNDARY_QLD_LAT1=${AISSTREAM_BOUNDARY_QLD_LAT1}
        - AISSTREAM_BOUNDARY_QLD_LON1=${AISSTREAM_BOUNDARY_QLD_LON1}
        - AISSTREAM_BOUNDARY_QLD_LAT2=${AISSTREAM_BOUNDARY_QLD_LAT2}
        - AISSTREAM_BOUNDARY_QLD_LON2=${AISSTREAM_BOUNDARY_QLD_LON2}
        - AISSTREAM_RETRY_SECS=${AISSTREAM_RETRY_SECS}
        - AISSTREAM_URI=${AISSTREAM_URI}
        - AISSTREAM_API_KEY=${AISSTREAM_API_KEY}
        - AISHUB_RETRY_SECS=${AISHUB_RETRY_SECS}
        - AISHUB_TIMEOUT_SECS=${AISHUB_TIMEOUT_SECS}
        - AISHUB_URI=${AISHUB_URI}
        - AMSA_RETRY_SECS=${AMSA_RETRY_SECS}
        - AMSA_TIMEOUT_SECS=${AMSA_TIMEOUT_SECS}
        - AMSA_URI=${AMSA_URI}
        - AISLOCAL_RETRY_SECS=${AISLOCAL_RETRY_SECS}
        - AISLOCAL_TIMEOUT_SECS=${AISLOCAL_TIMEOUT_SECS}
        - AISLOCAL_URI=${AISLOCAL_URI}
        - UDP_RETRY_SECS=${UDP_RETRY_SECS}
        - UDP_TIMEOUT_SECS=${UDP_TIMEOUT_SECS}
        - UDP_URI=${UDP_URI}
        - LOCAL_MONGODB_CONNECTION=${LOCAL_MONGODB_CONNECTION}
        - ATLAS_MONGODB_CONNECTION=${ATLAS_MONGODB_CONNECTION}
